import type { Topic } from './types'

export const godEvil: Topic = {
  id: "god-evil",
  title: "Is God Evil?",
  description: "Biblical accounts of divine judgment, destruction, and the question of God's moral character.",
  icon: "Shield",
  color: "orange",
  tags: [ "Scripture", "Biblical Judgment", "Apologetics", "Divine Command Theory"],
  content: `
    <h3>The Question of God's Character</h3>
    <p>Critics often accuse God of being evil based on biblical accounts where He commands destruction or directly causes death. They point to the flood, Sodom and Gomorrah, the Canaanite conquest, and individual judgments as evidence that the God of the Bible is immoral, violent, or evil.</p>

    <p><strong>Note:</strong> For broader questions about why evil exists in general, see our page on <a href="/categories/problem-of-evil" style="color: #007acc; text-decoration: underline;">If God, Why Evil?</a> This page focuses specifically on whether God's actions make Him evil.</p>

    <h4>The Foundation for Moral Judgment</h4>
    <p>Before examining specific cases, we must establish the proper foundation for moral judgment. If God exists and is the source of moral law (Divine Command Theory), then His actions must be evaluated by His own perfect nature, not by fallen human standards corrupted by sin<a href="https://www.reasonablefaith.org/writings/question-answer/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[1]</a>.</p>

    <h4>Key Principles for Understanding Divine Justice</h4>
    <p>When examining cases where God acts as judge, several biblical principles apply:</p>
    <p>• <strong>Creator's Authority:</strong> As the Creator of life, God has the absolute right to determine the length and circumstances of earthly existence<a href="https://denverjournal.denverseminary.edu/the-denver-journal-article/is-god-a-moral-monster-making-sense-of-the-old-testament-god/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[2]</a></p>
    <p>• <strong>Perfect Justice:</strong> God's judgments are always perfectly righteous, based on complete knowledge of human hearts and actions<a href="https://biblehub.com/topical/g/god" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[3]</a></p>
    <p>• <strong>Mercy Within Judgment:</strong> Even in acts of judgment, God provides opportunities for repentance and shows mercy to the righteous<a href="https://www.academia.edu/40890691/Biblical_Evidence_for_Gods_Patience_and_Mercy" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[4]</a></p>
    <p>• <strong>Temporal vs. Eternal:</strong> Physical death is not the ultimate evil—separation from God for eternity (spiritual death) is far worse<a href="https://www.gotquestions.org/physical-death.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[5]</a></p>
    <p>• <strong>Protection of the Innocent:</strong> In His perfect knowledge and nature as the Judge of all the earth, God ensures that innocent children who die go to His presence<a href="https://biblehub.com/topical/g/god" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[6]</a></p>

    <h4>God's Character Revealed</h4>
    <p>Rather than showing God to be evil, these biblical accounts reveal His perfect character:</p>
    <p>• <strong>Perfect Holiness:</strong> "Holy, holy, holy is the Lord God Almighty" - God cannot tolerate sin indefinitely (<a href="https://www.biblegateway.com/passage/?search=Isaiah+6:3&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Isaiah 6:3</a>)<a href="https://www.monergism.com/topics/attributes-god/holiness-god" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[7]</a></p>
    <p>• <strong>Perfect Justice:</strong> "The Rock, his work is perfect, for all his ways are justice" (<a href="https://www.biblegateway.com/passage/?search=Deuteronomy+32:4&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Deuteronomy 32:4</a>)<a href="https://biblehub.com/topical/g/god" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[8]</a></p>
    <p>• <strong>Perfect Love:</strong> "God is love" - His judgments flow from love for righteousness and the innocent (<a href="https://www.biblegateway.com/passage/?search=1+John+4:8&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">1 John 4:8</a>)<a href="https://www.ligonier.org/learn/articles/god-is-love-and-judgement" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[9]</a></p>
    <p>• <strong>Long-suffering Patience:</strong> "The Lord is not slow to fulfill his promise as some count slowness, but is patient toward you, not wishing that any should perish" (<a href="https://www.biblegateway.com/passage/?search=2+Peter+3:9&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">2 Peter 3:9</a>) - God's delay is an act of mercy<a href="https://biblehub.com/commentaries/2_peter/3-9.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[10]</a></p>

    <h4>The Ultimate Demonstration</h4>
    <p>The greatest proof that God is not evil is found in the cross. Rather than destroying humanity for sin, God sent His Son to bear the judgment we deserved: "But God shows his love for us in that while we were still sinners, Christ died for us" (<a href="https://www.biblegateway.com/passage/?search=Romans+5:8&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Romans 5:8</a>). The cross is the ultimate intersection where God's perfect justice and boundless love meet<a href="https://thecallednation.net/the-cross-where-love-and-justice-meet/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[11]</a>. The same God who judges sin also provides salvation from that judgment<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[12]</a>.</p>
  `,
  verses: [
    "Genesis 6:5", "Genesis 6:11", "Genesis 9:11-17", "2 Peter 2:5",
    "Genesis 18:16-19:29", "Genesis 19:4-11", "Genesis 18:22-33", "Genesis 19:12-16", "Ezekiel 16:49", "Jude 7", "2 Peter 2:6",
    "Exodus 7:14-12:30", "Exodus 1:8-22", "Exodus 12:13", "Exodus 12:38",
    "Joshua 6:1-11:23", "Genesis 15:16", "Leviticus 18:21-30", "Joshua 6:25", "Deuteronomy 20:14", "Matthew 5:28",
    "1 Samuel 15:1-33", "Exodus 17:8-16", "Deuteronomy 25:17-18", "Esther 3:1",
    "2 Samuel 6:6-7", "Numbers 4:15", "Leviticus 10:1-2", "Leviticus 10:3",
    "Numbers 16:1-35", "Acts 5:1-11", "Acts 5:11", "Acts 12:20-23",
    "Acts 12:1-4", "Acts 13:8-12", "2 Kings 17:7-18", "Amos 5:21-24",
    "Deuteronomy 28:64", "Jeremiah 29:10", "Numbers 14:26-35",
    "Isaiah 6:3", "Deuteronomy 32:4", "1 John 4:8", "2 Peter 3:9", "Romans 5:8"
  ],
  subtopics: [
    {
      id: "antediluvian-judgment",
      title: "The Great Flood",
      tags: ["flood", "noah", "genesis", "global-judgment"],
      content: `<strong>Biblical Account:</strong> <a href="https://www.biblegateway.com/passage/?search=Genesis+6:5-8:22&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 6:5-8:22</a> - God destroys the world with a flood, saving only Noah's family and the animals<a href="https://biblehub.com/commentaries/genesis/7-11.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[13]</a>.<br><br>
      
      <strong>Context and Justification:</strong><br>
      • <strong>Universal corruption:</strong> The judgment was necessary because "The Lord saw that the wickedness of man was great in the earth, and that every intention of the thoughts of his heart was only evil continually" (<a href="https://www.biblegateway.com/passage/?search=Genesis+6:5&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 6:5</a>)<a href="https://www.gotquestions.org/Noah-Flood.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[14]</a>.<br>
      • <strong>Violence and lawlessness:</strong> The earth was completely corrupted not only religiously but socially, being "filled with violence" (<a href="https://www.biblegateway.com/passage/?search=Genesis+6:11&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 6:11</a>)<a href="https://biblehub.com/commentaries/genesis/6-11.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[15]</a>.<br>
      • <strong>120-year warning period:</strong> God patiently gave humanity 120 years to repent while Noah built the ark and preached righteousness (<a href="https://www.biblegateway.com/passage/?search=2+Peter+2:5&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">2 Peter 2:5</a>), showing reluctance to judge<a href="https://www.christiananswers.net/q-eden/edn-c011.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[16]</a>.<br>
      • <strong>Preservation of the righteous:</strong> Noah and his family were spared because of their righteousness, demonstrating God's selective mercy amidst judgment<a href="https://www.gotquestions.org/Noah-Flood.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[14]</a>.<br>
      • <strong>New covenant promise:</strong> Following the flood, God established a covenant with Noah, promising never to destroy the earth by flood again (<a href="https://www.biblegateway.com/passage/?search=Genesis+9:11-17&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 9:11-17</a>), emphasizing His desire for cosmic stability<a href="https://www.ligonier.org/learn/articles/gods-covenant-with-noah" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[17]</a>.`
    },
    {
      id: "sodom-gomorrah",
      title: "Sodom and Gomorrah",
      tags: ["sodom", "gomorrah", "abraham", "lot"],
      content: `<strong>Biblical Account:</strong> <a href="https://www.biblegateway.com/passage/?search=Genesis+18:16-19:29&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 18:16-19:29</a> - God destroys Sodom, Gomorrah, and surrounding cities with fire and sulfur<a href="https://www.gotquestions.org/Sodom-and-Gomorrah.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[18]</a>.<br><br>
      
      <strong>Context and Justification:</strong><br>
      • <strong>Extreme wickedness:</strong> The city's sin included attempted gang rape of angels, but their deeper wickedness was defined as pride, gluttony, laziness, and a failure to help the poor and needy (<a href="https://www.biblegateway.com/passage/?search=Ezekiel+16:49&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Ezekiel 16:49</a>)<a href="https://www.bible.com/bible/compare/EZK.16.49-50,56" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[19]</a>.<br>
      • <strong>Abraham's intercession:</strong> God demonstrated His justice by proving His willingness to spare the cities for even ten righteous people, showing the judgment was a last resort due to total corruption (<a href="https://www.biblegateway.com/passage/?search=Genesis+18:22-33&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 18:22-33</a>)<a href="https://www.gotquestions.org/Abraham-Sodom-Gomorrah.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[20]</a>.<br>
      • <strong>Warning and escape:</strong> Lot and his family were warned and physically removed by angels before judgment fell (<a href="https://www.biblegateway.com/passage/?search=Genesis+19:12-16&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 19:12-16</a>)<a href="https://www.gotquestions.org/Abraham-Sodom-Gomorrah.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[20]</a>.<br>
      • <strong>Example for future:</strong> The destruction is used throughout Scripture as a physical and moral warning against rampant sexual immorality and social rebellion (<a href="https://www.biblegateway.com/passage/?search=Jude+7&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Jude 7</a>, <a href="https://www.biblegateway.com/passage/?search=2+Peter+2:6&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">2 Peter 2:6</a>)<a href="https://www.gotquestions.org/Sodom-and-Gomorrah.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[18]</a>.`
    },
    {
      id: "egyptian-plagues",
      title: "The Egyptian Plagues and Firstborn Deaths",
      tags: ["egypt", "plagues", "pharaoh", "exodus"],
      content: `<strong>Biblical Account:</strong> <a href="https://www.biblegateway.com/passage/?search=Exodus+7:14-12:30&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Exodus 7:14-12:30</a> - Ten plagues culminating in the death of all Egyptian firstborn<a href="https://www.gotquestions.org/ten-plagues-Egypt.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[21]</a>.<br><br>
      
      <strong>Context and Justification:</strong><br>
      • <strong>Centuries of oppression:</strong> The plagues were a righteous response to the centuries of slavery, forced labor, and state-sanctioned infanticide of Israelite male children (<a href="https://www.biblegateway.com/passage/?search=Exodus+1:8-22&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Exodus 1:8-22</a>)<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[12]</a>.<br>
      • <strong>Progressive warnings:</strong> Nine increasingly severe plagues gave Pharaoh multiple opportunities to repent, demonstrating God's patience<a href="https://www.gotquestions.org/ten-plagues-Egypt.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[21]</a>.<br>
      • <strong>Judgment on false gods:</strong> Each plague targeted specific Egyptian deities (e.g., the Nile god Hapi, the frog goddess Heqet), proving their powerlessness and demonstrating Yahweh’s supremacy to both Egyptians and Israelites<a href="https://www.ucg.org/learn/beyond-today-magazine/beyond-today-magazine-march-april-2019/exodus-plagues-judgment-egypts-gods" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[22]</a>.<br>
      • <strong>Protection available:</strong> Israelites and believing Egyptians who applied the Passover blood were protected (<a href="https://www.biblegateway.com/passage/?search=Exodus+12:13&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Exodus 12:13</a>), making the judgment conditional based on faith<a href="https://www.gotquestions.org/Passover-lamb.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[23]</a>.<br>
      • <strong>Liberation purpose:</strong> The entire process was aimed at freeing an enslaved people from genocidal oppression, making it an act of justice for the oppressed<a href="https://www.thegospelcoalition.org/blogs/trevin-wax/why-did-god-kill-the-firstborn-of-egypt/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[24]</a>.<br>
      • <strong>Mixed multitude:</strong> A "mixed multitude" of non-Israelites joined the exodus, indicating that God’s mercy and salvation were available to any who believed<a href="https://scispace.com/pdf/the-mixed-multitude-in-exodus-12-38-glorification-creation-2lq9wme191.pdf" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[25]</a>.`
    },
    {
      id: "canaanite-conquest",
      title: "The Canaanite Conquest",
      tags: ["canaanites", "joshua", "jericho", "conquest", "holy-war"],
      content: `<strong>Biblical Account:</strong> <a href="https://www.biblegateway.com/passage/?search=Joshua+6:1-11:23&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Joshua 6:1-11:23</a> - Israel conquers Canaan under divine command (known as <em>herem</em>) to destroy certain peoples<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[26]</a>.<br><br>
      
      <strong>Context and Justification:</strong><br>
      • <strong>400 years of patience:</strong> God waited 400 years (from Abraham to Moses) for Canaanite repentance before their judgment was carried out, showing profound forbearance (<a href="https://www.biblegateway.com/passage/?search=Genesis+15:16&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Genesis 15:16</a>)<a href="https://www.reasonablefaith.org/writings/question-answer/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[27]</a>.<br>
      • <strong>Extreme abominations:</strong> The judgment was delivered due to rampant, entrenched wickedness, specifically cited as child sacrifice, temple prostitution, and bestiality (<a href="https://www.biblegateway.com/passage/?search=Leviticus+18:21-30&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Leviticus 18:21-30</a>)<a href="https://www.asor.org/anetoday/2017/12/child-sacrifice-ancient-israel" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[28]</a>.<br>
      • <strong>Hyperbolic language:</strong> The command to "destroy completely" (<em>herem</em>) is understood in ancient Near Eastern military context as rhetorical language signifying a decisive, complete victory and removal, rather than literal biological genocide<a href="https://www.tyndalehouse.com/explorations/did-god-command-genocide/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[29]</a>.<br>
      • <strong>Archaeological Context:</strong> Archaeological evidence suggests key cities like Jericho were small, heavily fortified garrisons at the time, not vast, highly populated metropolitan centers, limiting the scope of destruction to military targets<a href="https://www.britannica.com/place/walls-of-Jericho" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[30]</a>.<br>
      • <strong>Survivors evidence:</strong> The repeated reappearance of Canaanites throughout the book of Judges and later history confirms the conquest was territorial and political, not total ethnic extermination<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[26]</a>.<br>
      • <strong>Examples of mercy:</strong> Rahab, a Canaanite woman, and her family were spared and integrated into Israel due to her faith, demonstrating that repentance allowed for salvation regardless of ethnic origin (<a href="https://www.biblegateway.com/passage/?search=Joshua+6:25&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Joshua 6:25</a>)<a href="https://www.gotquestions.org/life-Rahab.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[31]</a>.<br><br>
      
      <strong>Treatment of Captives and Women:</strong><br>
      • <strong>Law of the Captive Wife:</strong> In non-<em>herem</em> wars, the Law explicitly allowed taking non-Canaanite women as wives, but required a mandatory month-long waiting period for mourning, ritual cleansing (shaving head, paring nails), and the removal of her captive clothes before marriage. This process legally protected the woman from immediate sexual exploitation and forced the man to treat her as a wife, not a mere sex object (<a href="https://www.biblegateway.com/passage/?search=Deuteronomy+20:14&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Deuteronomy 20:14</a>)<a href="https://www.thetorah.com/article/the-captive-woman-at-the-intersection-of-war-and-family-laws" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[32]</a>.<br>
      • <strong>Jesus's Moral Standard:</strong> This regulation should be viewed in light of Jesus's moral teaching, which condemned the internal sin of lust itself, stating that to look at a woman with lustful intent is already adultery in the heart (<a href="https://www.biblegateway.com/passage/?search=Matthew+5:28&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Matthew 5:28</a>). Jesus affirmed an ultimate standard of holiness that transcended the legal minimums of the Old Testament<a href="https://learn.ligonier.org/devotionals/lustful-intent" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[33]</a>.`
    },
    {
      id: "amalekite-judgment",
      title: "The Amalekite Destruction",
      tags: ["amalekites", "saul", "samuel", "agag"],
      content: `<strong>Biblical Account:</strong> <a href="https://www.biblegateway.com/passage/?search=1+Samuel+15:1-33&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">1 Samuel 15:1-33</a> - God commands Saul to completely destroy the Amalekites including King Agag<a href="https://www.gotquestions.org/Amalekites.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[34]</a>.<br><br>
      
      <strong>Context and Justification:</strong><br>
      • <strong>Centuries of hostility:</strong> This command was a final act of justice following 200-400 years of persistent aggression against Israel, long after God had initially promised judgment<a href="https://www.gotquestions.org/Amalekites.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[34]</a>.<br>
      • <strong>Unprovoked aggression:</strong> The Amalekites were judged for their treacherous act of attacking the Israelites at Rephidim when they were weak and weary, specifically targeting the vulnerable at the rear of the camp (<a href="https://www.biblegateway.com/passage/?search=Exodus+17:8-16&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Exodus 17:8-16</a>, <a href="https://www.biblegateway.com/passage/?search=Deuteronomy+25:17-18&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Deuteronomy 25:17-18</a>)<a href="https://www.biblicaltraining.org/library/amalek" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[35]</a>.<br>
      • <strong>Genocidal intent:</strong> The Amalekites were not merely military opponents but were dedicated to the complete annihilation of Israel as a whole, making God's command an act of national defense for His chosen people<a href="https://www.gotquestions.org/Amalekites.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[34]</a>.<br>
      • <strong>Proportional judgment:</strong> King Agag was singled out by Samuel for his cruelty, being judged because his "sword has made women childless" (<a href="https://www.biblegateway.com/passage/?search=1+Samuel+15:33&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">1 Samuel 15:33</a>), showing the judgment was a just retribution for their wickedness<a href="https://www.thegospelcoalition.org/blogs/trevin-wax/why-did-god-tell-saul-to-kill-the-amalekites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[36]</a>.<br>
      • <strong>Future consequences:</strong> Saul's failure to completely execute the judgment led to the rise of Haman the Agagite, who later attempted to carry out a true genocide against the Jewish people in the book of Esther (<a href="https://www.biblegateway.com/passage/?search=Esther+3:1&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Esther 3:1</a>)<a href="https://www.biblestudytools.com/commentaries/gills-exposition-of-the-bible/1-samuel-15-3.html" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[37]</a>.`
    },
    {
      id: "individual-judgments",
      title: "Individual Death Judgments",
      tags: ["uzzah", "nadab", "abihu", "korah"],
      content: `<strong>Multiple Cases:</strong> These immediate judgments emphasize the severity of sin against a holy God and are meant to teach reverence to the entire community<a href="https://iphc.org/gso/2019/04/15/understanding-gods-justice-and-the-new-testament/" target="_blank" style="color: #007acc; text-decoration: none;">[38]</a>.<br><br>
      
      <strong>Uzzah and the Ark (<a href="https://www.biblegateway.com/passage/?search=2+Samuel+6:6-7&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">2 Samuel 6:6-7</a>):</strong><br>
      • <strong>Clear violation:</strong> Uzzah touched the Ark, an explicit violation of Mosaic Law, which mandated that only Kohathites could handle it, and then only by poles, never by hand (<a href="https://www.biblegateway.com/passage/?search=Numbers+4:15&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Numbers 4:15</a>)<a href="https://en.wikipedia.org/wiki/Uzzah" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[39]</a>.<br>
      • <strong>Irreverence toward holiness:</strong> The use of an oxcart (a non-Israelite method) to transport the Ark demonstrated a casual approach and lack of respect for God's sacred dwelling place, necessitating a severe public example<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[40]</a>.<br><br>
      
      <strong>Nadab and Abihu (<a href="https://www.biblegateway.com/passage/?search=Leviticus+10:1-2&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Leviticus 10:1-2</a>):</strong><br>
      • <strong>Unauthorized worship:</strong> They offered "strange fire" contrary to God's specific instructions immediately following the Tabernacle's dedication, demonstrating both carelessness and overstepping of their priestly role<a href="https://en.wikipedia.org/wiki/Nadab_and_Abihu" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[41]</a>.<br>
      • <strong>Holiness standard:</strong> Their immediate death established the non-negotiable principle that those who draw near to God in worship, especially priests, must treat Him as holy and follow divine protocol exactly (<a href="https://www.biblegateway.com/passage/?search=Leviticus+10:3&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Leviticus 10:3</a>)<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[40]</a>.<br><br>
      
      <strong>Korah's Rebellion (<a href="https://www.biblegateway.com/passage/?search=Numbers+16:1-35&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Numbers 16:1-35</a>):</strong><br>
      • <strong>Challenging divine authority:</strong> Korah's rebellion against Moses and Aaron was interpreted as a challenge to God's divinely appointed leadership and the order of the newly established nation<a href="https://biblicalcounseling.com/resource-library/articles/lessons-from-the-life-of-korah/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[42]</a>.<br>
      • <strong>Community preservation:</strong> The dramatic judgment (the earth swallowing the rebels) was a decisive action to prevent the spread of self-seeking ambition and anarchy that could have destroyed the entire community<a href="https://biblicalcounseling.com/resource-library/articles/lessons-from-the-life-of-korah/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[42]</a>.`
    },
    {
      id: "new-testament-judgments",
      title: "New Testament Divine Judgments",
      tags: ["ananias", "sapphira", "herod", "new-testament"],
      content: `<strong>Divine Judgment Continues:</strong> God's righteousness and justice are eternal attributes that continued to be demonstrated within the foundational period of the New Testament Church<a href="https://iphc.org/gso/2019/04/15/understanding-gods-justice-and-the-new-testament/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[38]</a>.<br><br>
      
      <strong>Ananias and Sapphira (<a href="https://www.biblegateway.com/passage/?search=Acts+5:1-11&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Acts 5:1-11</a>):</strong><br>
      • <strong>Deliberate deception:</strong> Their sin was not withholding money (which they had a right to do) but lying to the apostles and the Holy Spirit about their gift, showing deception and hypocrisy at the foundation of the church<a href="https://www.biblegateway.com/passage/?search=Acts%205&version=NIV" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[43]</a>.<br>
      • <strong>Early church purity:</strong> This swift, visible judgment protected the spiritual integrity and purity of the nascent Christian community from internal corruption and set a sober precedent for accountability<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[44]</a>.<br>
      • <strong>Fear restored:</strong> "Great fear came upon the whole church and upon all who heard of these things" (<a href="https://www.biblegateway.com/passage/?search=Acts+5:11&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Acts 5:11</a>)<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[44]</a>.<br><br>
      
      <strong>Herod Agrippa I (<a href="https://www.biblegateway.com/passage/?search=Acts+12:20-23&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Acts 12:20-23</a>):</strong><br>
      • <strong>Accepting worship:</strong> Herod allowed people to call him a god and failed to give glory to God, which is the sin of blasphemous pride<a href="https://biblehub.com/study/acts/12-23.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[45]</a>.<br>
      • <strong>Persecution of church:</strong> This judgment followed his active persecution of the church, including executing James and planning to execute Peter (<a href="https://www.biblegateway.com/passage/?search=Acts+12:1-4&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Acts 12:1-4</a>), demonstrating God's defense of His people<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[46]</a>.<br>
      • <strong>Eaten by worms:</strong> Struck down immediately by an angel, his gruesome death emphasized the seriousness of divine punishment for pride and blasphemy<a href="https://biblehub.com/study/acts/12-23.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[45]</a>.<br><br>
      
      <strong>Elymas the Sorcerer (<a href="https://www.biblegateway.com/passage/?search=Acts+13:8-12&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Acts 13:8-12</a>):</strong><br>
      • <strong>Opposing the gospel:</strong> Elymas actively opposed the Apostle Paul, trying to prevent the Roman proconsul from converting to faith<a href="https://www.bereanbiblesociety.org/the-sorcerer-of-israel/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[47]</a>.<br>
      • <strong>Temporary blindness:</strong> Paul pronounced a judgment of temporary blindness, which served as a sign to authenticate Paul's ministry to the proconsul<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[48]</a>.<br>
      • <strong>Merciful purpose:</strong> The blindness was temporary, mirroring Paul’s own conversion experience, and was intended to provide Elymas the opportunity for future repentance<a href="https://reknew.org/2017/12/pauls-blinding-elymas-response-paul-copan-5/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[49]</a>.`
    },
    {
      id: "israel-judgment",
      title: "God's Judgment on His Own People",
      tags: ["israel", "exile", "assyria", "babylon"],
      content: `<strong>Impartial Justice:</strong> God judged Israel when they sinned just as He judged the nations around them, proving His justice applies universally and is not biased toward His chosen people<a href="https://www.theberean.org/index.cfm/main/default/id/3510/judges-2-11-15.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[50]</a>.<br><br>
      
      <strong>Northern Kingdom Exile (722 BC):</strong><br>
      • <strong>Persistent rebellion:</strong> The Northern Kingdom suffered exile primarily for centuries of persistent idol worship (golden calves, Baals, Asherah) and walking in the customs of the surrounding nations despite prophetic warnings (<a href="https://www.biblegateway.com/passage/?search=2+Kings+17:7-18&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">2 Kings 17:7-18</a>)<a href="https://www.stepbible.org/?q=version=KingComments|reference=2Kgs.17.5-2Kgs.17.7" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[51]</a>.<br>
      • <strong>Social injustice:</strong> The prophets condemned the oppression of the poor and vulnerable while the wealthy maintained religious rituals, emphasizing that justice was a core part of the covenant (<a href="https://www.biblegateway.com/passage/?search=Amos+5:21-24&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Amos 5:21-24</a>)<a href="https://biblehub.com/study/amos/5-11.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[52]</a>.<br>
      • <strong>Covenant warnings fulfilled:</strong> The exile was the predetermined covenant consequence for national disobedience (<a href="https://www.biblegateway.com/passage/?search=Deuteronomy+28:64&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Deuteronomy 28:64</a>)<a href="https://www.stepbible.org/?q=version=KingComments|reference=2Kgs.17.5-2Kgs.17.7" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[51]</a>.<br><br>
      
      <strong>Babylonian Captivity (586 BC):</strong><br>
      • <strong>Extreme patience:</strong> God waited patiently, sending prophet after prophet for at least 23 years (Jeremiah’s ministry) before the final judgment was decreed, demonstrating long-suffering love (<a href="https://www.biblegateway.com/passage/?search=Jeremiah+25&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Jeremiah 25</a>)<a href="https://www.biblegateway.com/passage/?search=Jeremiah%2025&version=NRSVUE" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[53]</a>.<br>
      • <strong>Persistent warnings:</strong> Jeremiah's prophetic ministry lasted approximately 40 years, characterized by constant warnings and calls to repentance that were consistently ignored by the people and leaders<a href="https://biblehub.com/topical/j/jeremiah" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[54]</a>.<br>
      • <strong>Adopted Canaanite practices:</strong> Judah was judged severely for adopting the same abominations the Canaanites were punished for, including child sacrifice and temple prostitution, demonstrating God's impartiality in matters of holiness<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[55]</a>.<br>
      • <strong>Mercy within judgment:</strong> The exile was strictly limited to a 70-year period, accompanied by the promise of national restoration and return (<a href="https://www.biblegateway.com/passage/?search=Jeremiah+29:10&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Jeremiah 29:10</a>)<a href="https://biblehub.com/study/jeremiah/29-10.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[56]</a>.<br><br>
      
      <strong>Wilderness Wandering (<a href="https://www.biblegateway.com/passage/?search=Numbers+14:26-35&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Numbers 14:26-35</a>):</strong><br>
      • <strong>Faithless rebellion:</strong> The forty-year sentence was a direct judicial decree resulting from the nation's collective unbelief and refusal to enter the Promised Land after the spies' negative report, showing a failure to trust God's power (<a href="https://www.biblegateway.com/passage/?search=Numbers+14:26-35&version=NIV" target="_blank" style="color: #007acc; text-decoration: none;">Numbers 14:26-35</a>)<a href="https://biblehub.com/q/Why_40_years_of_wandering.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[57]</a>.<br>
      • <strong>Generational consequences:</strong> The judgment ensured the generation tainted by a slave mentality and unbelief would not corrupt the covenant promise, allowing the next generation to inherit the land with faith and discipline<a href="https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[55]</a>.<br>
      • <strong>Children preserved:</strong> Despite the death of the adult rebels, God sustained the nation by providing manna, water, and clothes that did not wear out, demonstrating continuous mercy and provision for the children who would inherit the promises<a href="https://biblehub.com/q/Why_40_years_of_wandering.htm" target="_blank" style="color: #007acc; text-decoration: none; font-size: 0.9em; vertical-align: super;">[57]</a>.`
    }
  ],
  sources: [
    // Core Primary Sources (Foundational Principles)
    "1. William Lane Craig - Reasonable Faith. 'Slaughter of the Canaanites' - Defense of divine command theory and moral foundations. https://www.reasonablefaith.org/writings/question-answer/slaughter-of-the-canaanites/",
    "2. Paul Copan - Denver Seminary Journal. 'Is God a Moral Monster? Making Sense of the Old Testament God' - Defense of God's authority over life and death. https://denverjournal.denverseminary.edu/the-denver-journal-article/is-god-a-moral-monster-making-sense-of-the-old-testament-god/",
    "3. Topical Bible: God's Omniscience and Justice - Discussion on the perfection and omniscience of divine judgment. https://biblehub.com/topical/g/god's_omniscience_and_justice.htm",
    "4. Dr. Michael Heiser - Academia.edu. 'Biblical Evidence for God's Patience and Mercy' - Theological perspective on God's willingness to spare. https://www.academia.edu/40890691/Biblical_Evidence_for_Gods_Patience_and_Mercy",
    "5. GotQuestions.org - 'How is physical death related to spiritual death?' - Focus on the temporal vs. eternal consequences of sin. https://www.gotquestions.org/physical-death.html",
    "6. Topical Bible: God's Perfect Judgment - On the justice of God, including the fate of the innocent. https://biblehub.com/topical/g/god's_perfect_judgment.htm",
    "7. Monergism - 'The Holiness of God' - Theological article on the essential holiness of God and its requirement for judgment. https://www.monergism.com/topics/attributes-god/holiness-god",
    "8. Topical Bible: God's Perfect Justice - Article on the perfection of God's justice as an attribute. https://biblehub.com/topical/g/god's_perfect_justice.htm",
    "9. Ligonier Ministries - 'God is Love and Judgment' - The paradox of God's love being the source of His righteous judgment. https://www.ligonier.org/learn/articles/god-is-love-and-judgement",
    "10. Bible Hub - '2 Peter 3:9 Commentary' - Theological exploration of God's long-suffering nature. https://biblehub.com/commentaries/2_peter/3-9.htm",
    "11. The Called Nation - 'The Cross: Where Love and Justice Meet' - The cross as the ultimate demonstration of God’s justice and salvation. https://thecallednation.net/the-cross-where-love-and-justice-meet/",
    "12. William Lane Craig - Reasonable Faith. 'The Problem of Evil' - Context of the Israelites' oppression (infanticide and slavery). https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/",

    // Flood and Noah Sources
    "13. David Guzik - Bible Hub Commentary. 'Commentary on Genesis 7:11' - Notes on the final judgment of the flood. https://biblehub.com/commentaries/genesis/7-11.htm",
    "14. GotQuestions.org - 'What was the meaning and purpose of the Flood?' - Context of the universal wickedness and God's purpose. https://www.gotquestions.org/Noah-Flood.html",
    "15. Bible Hub Commentaries: Genesis 6:11 - Focus on the violence and corruption leading to the flood. https://biblehub.com/commentaries/genesis/6-11.htm",
    "16. Christian Answers - 'The 120 Years of Grace' - Discussion on the 120-year grace period given before the flood. https://www.christiananswers.net/q-eden/edn-c011.html",
    "17. R. C. Sproul - Ligonier Ministries. 'God’s Covenant with Noah' - The covenant as a promise to never destroy the earth by flood again. https://www.ligonier.org/learn/articles/gods-covenant-with-noah",

    // Sodom and Gomorrah Sources
    "18. GotQuestions.org - 'What happened in Sodom and Gomorrah?' - Comprehensive coverage of extreme wickedness and destruction. https://www.gotquestions.org/Sodom-and-Gomorrah.html",
    "19. Bible.com: Ezekiel 16:49-50,56 - Biblical reference used to show Sodom's sin included pride, excess of food, and lack of aid to the poor. https://www.bible.com/bible/compare/EZK.16.49-50,56",
    "20. GotQuestions.org - 'What is the significance of Abraham's intercession for Sodom and Gomorrah?' - Covers Abraham's bargaining for the righteous. https://www.gotquestions.org/Abraham-Sodom-Gomorrah.html",

    // Egyptian Plagues Sources
    "21. GotQuestions.org - 'What were the 10 plagues of Egypt?' - Overview of the plagues and the progressive warnings. https://www.gotquestions.org/ten-plagues-Egypt.html",
    "22. United Church of God - 'The Exodus Plagues: Judgment on Egypt's Gods' - Analysis of each plague targeting specific Egyptian deities. https://www.ucg.org/learn/beyond-today-magazine/beyond-today-magazine-march-april-2019/exodus-plagues-judgment-egypts-gods",
    "23. GotQuestions.org - 'What is the significance of the Passover lamb?' - Protection available through the Passover blood. https://www.gotquestions.org/Passover-lamb.html",
    "24. Trevin Wax - The Gospel Coalition. 'Why Did God Kill the Firstborn of Egypt?' - Discussion on the plague's purpose as an act of justice and liberation. https://www.thegospelcoalition.org/blogs/trevin-wax/why-did-god-kill-the-firstborn-of-egypt/",
    "25. SciSpace - 'The Mixed Multitude in Exodus 12:38...' - Scholarly article on the composition of the mixed multitude and God's mercy. https://scispace.com/pdf/the-mixed-multitude-in-exodus-12-38-glorification-creation-2lq9wme191.pdf",

    // Canaanite Conquest Sources
    "26. William Lane Craig - Reasonable Faith. 'Slaughter of the Canaanites' - Context of herem and archaeological/survivor evidence. https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/",
    "27. William Lane Craig - Reasonable Faith. 'Slaughter of the Canaanites' - Reference to God's 400 years of patience (Genesis 15:16). https://www.reasonablefaith.org/writings/question-answer/slaughter-of-the-canaanites/",
    "28. ASOR ANE TODAY – 'Child Sacrifice in Ancient Israel' - Detailed discussion of the abominations. https://www.asor.org/anetoday/2017/12/child-sacrifice-ancient-israel",
    "29. Dr. Paul D. Wegner - Tyndale House. 'Did God Command Genocide?' - The use of hyperbolic language (herem) in ancient Near Eastern military texts. https://www.tyndalehouse.com/explorations/did-god-command-genocide/",
    "30. Britannica - 'Walls of Jericho' - Archaeological evidence for the military nature and scale of sites like Jericho. https://www.britannica.com/place/walls-of-Jericho",
    "31. GotQuestions.org - 'Who was Rahab in the Bible?' - Example of mercy and integration of a repenting Canaanite into Israel. https://www.gotquestions.org/life-Rahab.html",
    "32. TheTorah.com - 'The Captive Woman at the Intersection of War and Family Laws' - Analysis of Deuteronomy 20:14 laws on war captives/marriage protections. https://www.thetorah.com/article/the-captive-woman-at-the-intersection-of-war-and-family-laws",
    "33. Ligonier Ministries - 'Lustful Intent' - Exposition of Matthew 5:28 and Jesus's higher moral standard. https://learn.ligonier.org/devotionals/lustful-intent",

    // Amalekite Sources
    "34. GotQuestions.org - 'Who were the Amalekites?' - Centuries of hostility, unprovoked aggression, and genocidal intent. https://www.gotquestions.org/Amalekites.html",
    "35. Biblical Training - 'Amalek' - Historical context of the Amalekite attack on the weak at Rephidim. https://www.biblicaltraining.org/library/amalek",
    "36. Trevin Wax - The Gospel Coalition. 'Why Did God Tell Saul to Kill the Amalekites?' - Focus on the Amalekites' history of cruelty and child murder. https://www.thegospelcoalition.org/blogs/trevin-wax/why-did-god-tell-saul-to-kill-the-amalekites/",
    "37. John Gill - Bible Study Tools Commentary. '1 Samuel 15:3 Commentary' - Exposition on the future consequences of Saul's disobedience (Haman the Agagite). https://www.biblestudytools.com/commentaries/gills-exposition-of-the-bible/1-samuel-15-3.html",

    // Individual Judgment Sources
    "38. IPHC - 'Understanding God's Justice and the New Testament' - General article on divine judgment and righteousness continuing in the New Testament. https://iphc.org/gso/2019/04/15/understanding-gods-justice-and-the-new-testament/",
    "39. Wikipedia - 'Uzzah' - Analysis of the violation of handling commands (Numbers 4:15) and the teaching moment. https://en.wikipedia.org/wiki/Uzzah",
    "40. William Lane Craig - Reasonable Faith. 'The Problem of Evil' - Contextualizing Uzzah, Nadab, Abihu, and Korah in terms of God's holiness. https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/",
    "41. Wikipedia - 'Nadab and Abihu' - Coverage of unauthorized worship and the severity of priestly responsibility. https://en.wikipedia.org/wiki/Nadab_and_Abihu",
    "42. ACBC - 'Lessons from the Life of Korah' - Analysis of challenging divine authority and the goal of community preservation. https://biblicalcounseling.com/resource-library/articles/lessons-from-the-life-of-korah/",

    // New Testament Judgment Sources
    "43. Bible Gateway - Acts 5 NIV - The original text for Ananias and Sapphira, demonstrating the severity of lying to the Holy Spirit. https://www.biblegateway.com/passage/?search=Acts%205&version=NIV",
    "44. William Lane Craig - Reasonable Faith. 'Slaughter of the Canaanites' - Used to support the point on Ananias and Sapphira testing God and restoring fear. https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/slaughter-of-the-canaanites/",
    "45. Bible Hub Study Bible: Acts 12:23 - Coverage of Herod Agrippa's death for accepting worship and blasphemy. https://biblehub.com/study/acts/12-23.htm",
    "46. William Lane Craig - Reasonable Faith. 'The Problem of Evil' - Context of Herod's persecution of the church (Acts 12:1-4). https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/",
    "47. Berean Bible Society - 'The Sorcerer of Israel – Acts 13:6-12' - Analysis of opposing the gospel and the judgment of temporary blindness. https://www.bereanbiblesociety.org/the-sorcerer-of-israel/",
    "48. William Lane Craig - Reasonable Faith. 'The Problem of Evil' - Supporting statement on the temporary blindness as a warning. https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/",
    "49. Greg Boyd - ReKnew. 'Paul's Blinding of Elymas: A Response to Paul Copan' - Focuses on the merciful, temporary nature of the judgment for repentance. https://reknew.org/2017/12/pauls-blinding-elymas-response-paul-copan-5/",

    // Israel Judgment Sources
    "50. The Berean - 'God's Judgment on Nations: Israel, Judah...' - Explains God's universal justice applying to His chosen people. https://www.theberean.org/index.cfm/main/default/id/3510/judges-2-11-15.htm",
    "51. STEP Bible - '2 Kings 17:5-7 | Israel Carried Away Into Exile' - Persistent rebellion and covenant warnings fulfilled in the Northern Kingdom's exile. https://www.stepbible.org/?q=version=KingComments|reference=2Kgs.17.5-2Kgs.17.7",
    "52. Bible Hub Study Bible: Amos 5:11 - Focus on the prophet Amos's message of social injustice and religious hypocrisy. https://biblehub.com/study/amos/5-11.htm",
    "53. Bible Gateway - Jeremiah 25 NRSVUE - Context of extreme patience and 23 years of warnings before the Babylonian judgment. https://www.biblegateway.com/passage/?search=Jeremiah%2025&version=NRSVUE",
    "54. Bible Hub Topical Bible: Jeremiah's Prophetic Warning - Coverage of Jeremiah's 40-year ministry and constant warnings. https://biblehub.com/topical/j/jeremiah's_prophetic_warning.htm",
    "55. William Lane Craig - Reasonable Faith. 'The Problem of Evil' - Specific reference to Judah adopting Canaanite abominations (child sacrifice) and the generational consequences in the wilderness. https://www.reasonablefaith.org/writings/popular-writings/existence-nature-of-god/the-problem-of-evil/",
    "56. Bible Hub Study Bible: Jeremiah 29:10 - Coverage of the 70-year limit and the promise of restoration. https://biblehub.com/study/jeremiah/29-10.htm",
    "57. Bible Hub Q&A - 'Why did God let the Israelites wander for 40 years in Numbers 14:33?' - Analysis of faithless rebellion and the preservation of the next generation. https://biblehub.com/q/Why_40_years_of_wandering.htm"
  ],
  lastUpdated: "18-11-2025"
}